### ISSUE TITLE
为啥引用老是失败呢

### ISSUE THREAD

**Issue by zklaushhh** [ledao/arrgo#5]
引用显示如下 
github.com/ledao/arrgo: github.com/ledao/arrgo@v0.0.2: parsing go.mod:
        module declares its path as: arrgo
                but was required as: github.com/ledao/arrgo

哪位老哥帮帮忙？？

**Comment by ledao** [comment]
你好，问题已经修复，请使用：

```
require github.com/ledao/arrgo v0.0.3
```

**Comment by ledao** [comment]
@zklaushhh

**Comment by zklaushhh** [comment]
谢谢大佬！

**Comment by ledao** [comment]
问题解决
